# Generated by Django 5.2.4 on 2025-08-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('createdAt', models.DateTimeField()),
                ('dotStyle', models.CharField(max_length=20)),
                ('eyeStyle', models.CharField(max_length=20)),
                ('isPublic', models.BooleanField(default=True)),
                ('logoImage', models.TextField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
