# Generated by Django 5.2.4 on 2025-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='color2',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='qr',
            name='logoImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
