# Generated by Django 5.2.4 on 2025-08-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_qr_color2_alter_qr_logoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
